spring:
  datasource:
    url: jdbc:postgresql://localhost/invoice_management
    username: postgres
    password: NOVIANTO
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true

